package:
  name: dekupl-run
  version: "1.1"

source:
  git_url: https://github.com/Transipedia/dekupl-run

build:
  number: 2
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - boost
    - zlib

  run:
    - pigz
    - jellyfish >2.2.0
    - snakemake <5.2.0
    - r-base
    - rpy2
    - r-rcolorbrewer
    - r-pheatmap
    - r-foreach
    - r-doparallel
    - bioconductor-deseq2

test:
  commands:
    - dekupl-run -v

about:
  home: https://github.com/Transipedia/dekupl-run
  license: MIT
  license_file: LICENSE


