options(repos='http://cran.rstudio.com/')
install.packages("RColorBrewer")
install.packages("pheatmap")
install.packages("foreach")
install.packages("doParallel")
source("http://bioconductor.org/biocLite.R")
biocLite("DESeq2")
install.packages("https://cran.r-project.org/src/contrib/Archive/latticeExtra/latticeExtra_0.6-28.tar.gz", dependencies=TRUE)
install.packages("https://cran.r-project.org/src/contrib/Archive/Hmisc/Hmisc_4.2-0.tar.gz", dependencies=TRUE)
biocLite("DESeq2")
biocLite("limma")
biocLite("edgeR")
