options(repos='http://cran.rstudio.com/')
install.packages("RColorBrewer")
install.packages("pheatmap")
install.packages("foreach")
install.packages("doParallel")
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
